### 1. ADIM: Tüm İlanları Listele (Buradan ID'leri bulacağız)
GET https://unicycle-api.onrender.com/api/products

### --------------------------------------------------------

### 2. ADIM: İstemediğin İlanları Sil (X, Y ve Z yerine bulduğun numaraları yaz)

### 1. İlanı Sil
DELETE https://unicycle-api.onrender.com/api/products/3

### 2. İlanı Sil
DELETE https://unicycle-api.onrender.com/api/products/4

### 3. İlanı Sil
DELETE https://unicycle-api.onrender.com/api/products/5